version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:3000"
    command: npm run dev



# the use of this file is to rebuild and run the project every time there is a modification in the code 